name = "ai-digest-bot"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_NAME = "AI-дайджест"
BOT_TOPIC = "Всё об искусственном интеллекте за неделю"
ADMIN_IDS = "1271633868"
CHANNEL_ID = "-1001859702206"
INVEST_CHANNEL = "-1001644114424"
BOT_TOKEN = "8341305314:AAGgyDgXQ8L3JKr7NqukTC4vSsNiJNIzYAc"

[[d1_databases]]
binding = "DB"
database_name = "ai-digest-bot-db"
database_id = "cee284b6-8392-4db8-8389-59bd9eafc869"

[[kv_namespaces]]
binding = "RAG_STORE"
id = "d7fe61b4e39b4607af339e57cee0bca1"

[[kv_namespaces]]
binding = "CONVERSATION_STORE"
id = "f3adf57a2e77412e8bb8dd38bb6394e4"

[ai]
binding = "AI"

[triggers]
crons = ["0 9 * * *", "0 14 * * *", "30 19 * * *"]
